### ISSUE TITLE
Welche Projektion wird für lat/lon der Tankstellen verwendet?

### ISSUE THREAD

**Issue by c-goetz** [InformatiCup/InformatiCup2018#6]

**Comment by c-goetz** [comment]
Mit Projektion meine ich eigentlich welches Referenzsystem verwendet wird. Also zB epsg 4326.

**Comment by AlexPaar** [comment]
Wofür ist denn die Projektion wichtig? Für die Abstände der Tankstellen zueinander kann bitte einfach die Formel für die Großkreisentfernung aus der Aufgabenstellung verwendet werden.

**Comment by c-goetz** [comment]
Wir möchten zur Kategorisierung von Autobahntankstellen die kürzeste Entfernung zu einer Autobahn berechnen und einen Schwellenwert festlegen. Die verwendete Library benötigt dafür den EPSG Code der Geometrien.

**Comment by AlexPaar** [comment]
Die Recherche läuft...

**Comment by AlexPaar** [comment]
Also, in dem [Datenmodell für die Markttransparenzstelle für Kraftstoffe](https://www.bft.de/files/9113/7396/7582/MDM_Datenmodell_MTS-K_01-00-00.pdf) ist [ETRS89](https://www.wuppertal.de/rathaus-buergerservice/medien/dokumente/Faltblatt_ETRS89_5-2009.pdf) referenziert (Seite 11) mit dem Zusatz: "Koordinaten nach WGS84 können ebenfalls (ohne Umwandlung) verwendet werden". Bitte meldet Euch nochmal wenn diese Infos nicht ausreichen.

**Comment by c-goetz** [comment]
Das passt. Vielen Dank!
